#ifndef XML10_H
#define XML10_H

#include "xmlTypes.h"

/* XML 1.0 grammar symbols */
enum {
  XML10_document,
  XML10_prolog,
  XML10_element,
  XML10_MiscAny,
  XML10_Char,
  XML10_CHAR,
  XML10_Name,
  XML10_NAME,
  XML10_Names,
  XML10_X20,
  XML10_Nmtoken,
  XML10_NMTOKEN,
  XML10_Nmtokens,
  XML10_EntityValue,
  XML10_ENTITYVALUE,
  XML10_AttValue,
  XML10_ATTVALUE,
  XML10_SystemLiteral,
  XML10_SYSTEMLITERAL,
  XML10_PubidLiteral,
  XML10_PUBIDLITERAL,
  XML10_CharData,
  XML10_CHARDATA,
  XML10_Comment,
  XML10_COMMENT_BEG,
  XML10_COMMENT,
  XML10_COMMENT_END,
  XML10_PITarget,
  XML10_PITARGET,
  XML10_PI,
  XML10_PI_BEG,
  XML10_PI_END,
  XML10_S,
  XML10_PI_INTERIOR,
  XML10_CDSect,
  XML10_CDStart,
  XML10_CData,
  XML10_CDEnd,
  XML10_CDSTART,
  XML10_CDATA,
  XML10_CDEND,
  XML10_XMLDeclMaybe,
  XML10_doctypedecl,
  XML10_XMLDecl,
  XML10_XML_BEG,
  XML10_VersionInfo,
  XML10_EncodingDeclMaybe,
  XML10_SDDeclMaybe,
  XML10_SMaybe,
  XML10_XML_END,
  XML10_VERSION,
  XML10_Eq,
  XML10_SQUOTE,
  XML10_VersionNum,
  XML10_DQUOTE,
  XML10_EQUAL,
  XML10_VERSIONNUM,
  XML10_Misc,
  XML10_DOCTYPE_BEG,
  XML10_XTAG_END,
  XML10_LBRACKET,
  XML10_intSubset,
  XML10_RBRACKET,
  XML10_ExternalID,
  XML10_DeclSep,
  XML10_PEReference,
  XML10_intSubsetUnitAny,
  XML10_markupdecl,
  XML10_elementdecl,
  XML10_AttlistDecl,
  XML10_EntityDecl,
  XML10_NotationDecl,
  XML10_extSubset,
  XML10_extSubsetDecl,
  XML10_TextDecl,
  XML10_extSubsetDeclUnitAny,
  XML10_SDDecl,
  XML10_STANDALONE,
  XML10_YES,
  XML10_NO,
  XML10_EmptyElemTag,
  XML10_STag,
  XML10_content,
  XML10_ETag,
  XML10_XTAG_BEG,
  XML10_STagInteriorAny,
  XML10_STAG_END,
  XML10_Attribute,
  XML10_ETAG_BEG,
  XML10_ETAG_END,
  XML10_CharDataMaybe,
  XML10_ContentInteriorAny,
  XML10_EmptyElemTagInteriorAny,
  XML10_EMPTYELEMTAG_END,
  XML10_ELEMENTDECL_BEG,
  XML10_contentspec,
  XML10_EMPTY,
  XML10_ANY,
  XML10_Mixed,
  XML10_children,
  XML10_choice,
  XML10_QuantifierMaybe,
  XML10_seq,
  XML10_cp,
  XML10_LPAREN,
  XML10_ChoiceInteriorMany,
  XML10_RPAREN,
  XML10_SeqInteriorAny,
  XML10_PCDATA,
  XML10_MixedInteriorAny,
  XML10_RPARENSTAR,
  XML10_ATTLIST_BEG,
  XML10_AttDefAny,
  XML10_AttDef,
  XML10_AttType,
  XML10_DefaultDecl,
  XML10_StringType,
  XML10_TokenizedType,
  XML10_EnumeratedType,
  XML10_STRINGTYPE,
  XML10_TYPE_ID,
  XML10_TYPE_IDREF,
  XML10_TYPE_IDREFS,
  XML10_TYPE_ENTITY,
  XML10_TYPE_ENTITIES,
  XML10_TYPE_NMTOKEN,
  XML10_TYPE_NMTOKENS,
  XML10_NotationType,
  XML10_Enumeration,
  XML10_NOTATION,
  XML10_NotationTypeInteriorAny,
  XML10_EnumerationInteriorAny,
  XML10_REQUIRED,
  XML10_IMPLIED,
  XML10_FIXED,
  XML10_conditionalSect,
  XML10_includeSect,
  XML10_ignoreSect,
  XML10_SECT_BEG,
  XML10_INCLUDE,
  XML10_SECT_END,
  XML10_IGNORE,
  XML10_ignoreSectContentsAny,
  XML10_ignoreSectContents,
  XML10_Ignore,
  XML10_ignoreSectContentsInteriorAny,
  XML10_IGNORE_INTERIOR,
  XML10_CharRef,
  XML10_CHARREF,
  XML10_Reference,
  XML10_EntityRef,
  XML10_ENTITYREF,
  XML10_PEREFERENCE,
  XML10_GEDecl,
  XML10_PEDecl,
  XML10_EDECL_BEG,
  XML10_EntityDef,
  XML10_PERCENT,
  XML10_PEDef,
  XML10_NDataDecl,
  XML10_SYSTEM,
  XML10_PUBLIC,
  XML10_NDATA,
  XML10_VersionInfoMaybe,
  XML10_EncodingDecl,
  XML10_extParsedEnt,
  XML10_ENCODING,
  XML10_EncName,
  XML10_ENCNAME,
  XML10_NOTATION_BEG,
  XML10_PublicID,
  XML10_ContentInterior,
  XML10_intSubsetUnit,
  XML10_extSubsetDeclUnit,
  XML10_STagInterior,
  XML10_EmptyElemTagInterior,
  XML10_Quantifier,
  XML10_QUESTION_MARK,
  XML10_STAR,
  XML10_PLUS,
  XML10_ChoiceInterior,
  XML10_PIPE,
  XML10_SeqInterior,
  XML10_COMMA,
  XML10_MixedInterior,
  XML10_NotationTypeInterior,
  XML10_EnumerationInterior
};

struct sXmlSymbolId aXml10SymbolId[] = {
  { -1, XML10_document, "document" },
  { -1, XML10_prolog, "prolog" },
  { -1, XML10_element, "element" },
  { -1, XML10_MiscAny, "MiscAny" },
  { -1, XML10_Char, "Char" },
  { -1, XML10_CHAR, "CHAR" },
  { -1, XML10_Name, "Name" },
  { -1, XML10_NAME, "NAME" },
  { -1, XML10_Names, "Names" },
  { -1, XML10_X20, "X20" },
  { -1, XML10_Nmtoken, "Nmtoken" },
  { -1, XML10_NMTOKEN, "NMTOKEN" },
  { -1, XML10_Nmtokens, "Nmtokens" },
  { -1, XML10_EntityValue, "EntityValue" },
  { -1, XML10_ENTITYVALUE, "ENTITYVALUE" },
  { -1, XML10_AttValue, "AttValue" },
  { -1, XML10_ATTVALUE, "ATTVALUE" },
  { -1, XML10_SystemLiteral, "SystemLiteral" },
  { -1, XML10_SYSTEMLITERAL, "SYSTEMLITERAL" },
  { -1, XML10_PubidLiteral, "PubidLiteral" },
  { -1, XML10_PUBIDLITERAL, "PUBIDLITERAL" },
  { -1, XML10_CharData, "CharData" },
  { -1, XML10_CHARDATA, "CHARDATA" },
  { -1, XML10_Comment, "Comment" },
  { -1, XML10_COMMENT_BEG, "COMMENT_BEG" },
  { -1, XML10_COMMENT, "COMMENT" },
  { -1, XML10_COMMENT_END, "COMMENT_END" },
  { -1, XML10_PITarget, "PITarget" },
  { -1, XML10_PITARGET, "PITARGET" },
  { -1, XML10_PI, "PI" },
  { -1, XML10_PI_BEG, "PI_BEG" },
  { -1, XML10_PI_END, "PI_END" },
  { -1, XML10_S, "S" },
  { -1, XML10_PI_INTERIOR, "PI_INTERIOR" },
  { -1, XML10_CDSect, "CDSect" },
  { -1, XML10_CDStart, "CDStart" },
  { -1, XML10_CData, "CData" },
  { -1, XML10_CDEnd, "CDEnd" },
  { -1, XML10_CDSTART, "CDSTART" },
  { -1, XML10_CDATA, "CDATA" },
  { -1, XML10_CDEND, "CDEND" },
  { -1, XML10_XMLDeclMaybe, "XMLDeclMaybe" },
  { -1, XML10_doctypedecl, "doctypedecl" },
  { -1, XML10_XMLDecl, "XMLDecl" },
  { -1, XML10_XML_BEG, "XML_BEG" },
  { -1, XML10_VersionInfo, "VersionInfo" },
  { -1, XML10_EncodingDeclMaybe, "EncodingDeclMaybe" },
  { -1, XML10_SDDeclMaybe, "SDDeclMaybe" },
  { -1, XML10_SMaybe, "SMaybe" },
  { -1, XML10_XML_END, "XML_END" },
  { -1, XML10_VERSION, "VERSION" },
  { -1, XML10_Eq, "Eq" },
  { -1, XML10_SQUOTE, "SQUOTE" },
  { -1, XML10_VersionNum, "VersionNum" },
  { -1, XML10_DQUOTE, "DQUOTE" },
  { -1, XML10_EQUAL, "EQUAL" },
  { -1, XML10_VERSIONNUM, "VERSIONNUM" },
  { -1, XML10_Misc, "Misc" },
  { -1, XML10_DOCTYPE_BEG, "DOCTYPE_BEG" },
  { -1, XML10_XTAG_END, "XTAG_END" },
  { -1, XML10_LBRACKET, "LBRACKET" },
  { -1, XML10_intSubset, "intSubset" },
  { -1, XML10_RBRACKET, "RBRACKET" },
  { -1, XML10_ExternalID, "ExternalID" },
  { -1, XML10_DeclSep, "DeclSep" },
  { -1, XML10_PEReference, "PEReference" },
  { -1, XML10_intSubsetUnitAny, "intSubsetUnitAny" },
  { -1, XML10_markupdecl, "markupdecl" },
  { -1, XML10_elementdecl, "elementdecl" },
  { -1, XML10_AttlistDecl, "AttlistDecl" },
  { -1, XML10_EntityDecl, "EntityDecl" },
  { -1, XML10_NotationDecl, "NotationDecl" },
  { -1, XML10_extSubset, "extSubset" },
  { -1, XML10_extSubsetDecl, "extSubsetDecl" },
  { -1, XML10_TextDecl, "TextDecl" },
  { -1, XML10_extSubsetDeclUnitAny, "extSubsetDeclUnitAny" },
  { -1, XML10_SDDecl, "SDDecl" },
  { -1, XML10_STANDALONE, "STANDALONE" },
  { -1, XML10_YES, "YES" },
  { -1, XML10_NO, "NO" },
  { -1, XML10_EmptyElemTag, "EmptyElemTag" },
  { -1, XML10_STag, "STag" },
  { -1, XML10_content, "content" },
  { -1, XML10_ETag, "ETag" },
  { -1, XML10_XTAG_BEG, "XTAG_BEG" },
  { -1, XML10_STagInteriorAny, "STagInteriorAny" },
  { -1, XML10_STAG_END, "STAG_END" },
  { -1, XML10_Attribute, "Attribute" },
  { -1, XML10_ETAG_BEG, "ETAG_BEG" },
  { -1, XML10_ETAG_END, "ETAG_END" },
  { -1, XML10_CharDataMaybe, "CharDataMaybe" },
  { -1, XML10_ContentInteriorAny, "ContentInteriorAny" },
  { -1, XML10_EmptyElemTagInteriorAny, "EmptyElemTagInteriorAny" },
  { -1, XML10_EMPTYELEMTAG_END, "EMPTYELEMTAG_END" },
  { -1, XML10_ELEMENTDECL_BEG, "ELEMENTDECL_BEG" },
  { -1, XML10_contentspec, "contentspec" },
  { -1, XML10_EMPTY, "EMPTY" },
  { -1, XML10_ANY, "ANY" },
  { -1, XML10_Mixed, "Mixed" },
  { -1, XML10_children, "children" },
  { -1, XML10_choice, "choice" },
  { -1, XML10_QuantifierMaybe, "QuantifierMaybe" },
  { -1, XML10_seq, "seq" },
  { -1, XML10_cp, "cp" },
  { -1, XML10_LPAREN, "LPAREN" },
  { -1, XML10_ChoiceInteriorMany, "ChoiceInteriorMany" },
  { -1, XML10_RPAREN, "RPAREN" },
  { -1, XML10_SeqInteriorAny, "SeqInteriorAny" },
  { -1, XML10_PCDATA, "PCDATA" },
  { -1, XML10_MixedInteriorAny, "MixedInteriorAny" },
  { -1, XML10_RPARENSTAR, "RPARENSTAR" },
  { -1, XML10_ATTLIST_BEG, "ATTLIST_BEG" },
  { -1, XML10_AttDefAny, "AttDefAny" },
  { -1, XML10_AttDef, "AttDef" },
  { -1, XML10_AttType, "AttType" },
  { -1, XML10_DefaultDecl, "DefaultDecl" },
  { -1, XML10_StringType, "StringType" },
  { -1, XML10_TokenizedType, "TokenizedType" },
  { -1, XML10_EnumeratedType, "EnumeratedType" },
  { -1, XML10_STRINGTYPE, "STRINGTYPE" },
  { -1, XML10_TYPE_ID, "TYPE_ID" },
  { -1, XML10_TYPE_IDREF, "TYPE_IDREF" },
  { -1, XML10_TYPE_IDREFS, "TYPE_IDREFS" },
  { -1, XML10_TYPE_ENTITY, "TYPE_ENTITY" },
  { -1, XML10_TYPE_ENTITIES, "TYPE_ENTITIES" },
  { -1, XML10_TYPE_NMTOKEN, "TYPE_NMTOKEN" },
  { -1, XML10_TYPE_NMTOKENS, "TYPE_NMTOKENS" },
  { -1, XML10_NotationType, "NotationType" },
  { -1, XML10_Enumeration, "Enumeration" },
  { -1, XML10_NOTATION, "NOTATION" },
  { -1, XML10_NotationTypeInteriorAny, "NotationTypeInteriorAny" },
  { -1, XML10_EnumerationInteriorAny, "EnumerationInteriorAny" },
  { -1, XML10_REQUIRED, "REQUIRED" },
  { -1, XML10_IMPLIED, "IMPLIED" },
  { -1, XML10_FIXED, "FIXED" },
  { -1, XML10_conditionalSect, "conditionalSect" },
  { -1, XML10_includeSect, "includeSect" },
  { -1, XML10_ignoreSect, "ignoreSect" },
  { -1, XML10_SECT_BEG, "SECT_BEG" },
  { -1, XML10_INCLUDE, "INCLUDE" },
  { -1, XML10_SECT_END, "SECT_END" },
  { -1, XML10_IGNORE, "IGNORE" },
  { -1, XML10_ignoreSectContentsAny, "ignoreSectContentsAny" },
  { -1, XML10_ignoreSectContents, "ignoreSectContents" },
  { -1, XML10_Ignore, "Ignore" },
  { -1, XML10_ignoreSectContentsInteriorAny, "ignoreSectContentsInteriorAny" },
  { -1, XML10_IGNORE_INTERIOR, "IGNORE_INTERIOR" },
  { -1, XML10_CharRef, "CharRef" },
  { -1, XML10_CHARREF, "CHARREF" },
  { -1, XML10_Reference, "Reference" },
  { -1, XML10_EntityRef, "EntityRef" },
  { -1, XML10_ENTITYREF, "ENTITYREF" },
  { -1, XML10_PEREFERENCE, "PEREFERENCE" },
  { -1, XML10_GEDecl, "GEDecl" },
  { -1, XML10_PEDecl, "PEDecl" },
  { -1, XML10_EDECL_BEG, "EDECL_BEG" },
  { -1, XML10_EntityDef, "EntityDef" },
  { -1, XML10_PERCENT, "PERCENT" },
  { -1, XML10_PEDef, "PEDef" },
  { -1, XML10_NDataDecl, "NDataDecl" },
  { -1, XML10_SYSTEM, "SYSTEM" },
  { -1, XML10_PUBLIC, "PUBLIC" },
  { -1, XML10_NDATA, "NDATA" },
  { -1, XML10_VersionInfoMaybe, "VersionInfoMaybe" },
  { -1, XML10_EncodingDecl, "EncodingDecl" },
  { -1, XML10_extParsedEnt, "extParsedEnt" },
  { -1, XML10_ENCODING, "ENCODING" },
  { -1, XML10_EncName, "EncName" },
  { -1, XML10_ENCNAME, "ENCNAME" },
  { -1, XML10_NOTATION_BEG, "NOTATION_BEG" },
  { -1, XML10_PublicID, "PublicID" },
  { -1, XML10_ContentInterior, "ContentInterior" },
  { -1, XML10_intSubsetUnit, "intSubsetUnit" },
  { -1, XML10_extSubsetDeclUnit, "extSubsetDeclUnit" },
  { -1, XML10_STagInterior, "STagInterior" },
  { -1, XML10_EmptyElemTagInterior, "EmptyElemTagInterior" },
  { -1, XML10_Quantifier, "Quantifier" },
  { -1, XML10_QUESTION_MARK, "QUESTION_MARK" },
  { -1, XML10_STAR, "STAR" },
  { -1, XML10_PLUS, "PLUS" },
  { -1, XML10_ChoiceInterior, "ChoiceInterior" },
  { -1, XML10_PIPE, "PIPE" },
  { -1, XML10_SeqInterior, "SeqInterior" },
  { -1, XML10_COMMA, "COMMA" },
  { -1, XML10_MixedInterior, "MixedInterior" },
  { -1, XML10_NotationTypeInterior, "NotationTypeInterior" },
  { -1, XML10_EnumerationInterior, "EnumerationInterior" }
};

#endif
