/*
 * Tue Apr 15 10:36:46 2014
 *
 * Generated with:
 * perl GenerateLowLevel.pl --bnf bnf/xml10.bnf --prefix xml10 --output xml10.c
 *
 */

#ifndef XML10_H
#define XML10_H

#include "xmlTypes.h"

enum {
    XML10_ANY = 0                           ,
    XML10_ATTLIST_BEG                       ,
    XML10_ATTVALUE                          ,
    XML10_Any                               ,
    XML10_AttDef                            ,
    XML10_AttDefAny                         ,
    XML10_AttType                           ,
    XML10_AttValue                          ,
    XML10_AttlistBeg                        ,
    XML10_AttlistDecl                       ,
    XML10_AttlistEnd                        ,
    XML10_Attribute                         ,
    XML10_CDATA                             ,
    XML10_CDEND                             ,
    XML10_CDEnd                             ,
    XML10_CDSTART                           ,
    XML10_CDSect                            ,
    XML10_CDStart                           ,
    XML10_CData                             ,
    XML10_CHAR                              ,
    XML10_CHARDATA                          ,
    XML10_CHARREF                           ,
    XML10_COMMA                             ,
    XML10_COMMENT                           ,
    XML10_COMMENT_BEG                       ,
    XML10_COMMENT_END                       ,
    XML10_Char                              ,
    XML10_CharData                          ,
    XML10_CharDataMaybe                     ,
    XML10_CharRef                           ,
    XML10_ChoiceInterior                    ,
    XML10_ChoiceInteriorMany                ,
    XML10_Comma                             ,
    XML10_Comment                           ,
    XML10_CommentBeg                        ,
    XML10_CommentEnd                        ,
    XML10_CommentInterior                   ,
    XML10_ContentInterior                   ,
    XML10_ContentInteriorAny                ,
    XML10_DOCTYPE_BEG                       ,
    XML10_DQUOTE                            ,
    XML10_DeclSep                           ,
    XML10_DefaultDecl                       ,
    XML10_DoctypeBeg                        ,
    XML10_DoctypeEnd                        ,
    XML10_Dquote                            ,
    XML10_EDECL_BEG                         ,
    XML10_ELEMENTDECL_BEG                   ,
    XML10_EMPTY                             ,
    XML10_EMPTYELEMTAG_END                  ,
    XML10_ENCNAME                           ,
    XML10_ENCODING                          ,
    XML10_ENTITYREF                         ,
    XML10_ENTITYVALUE                       ,
    XML10_EQUAL                             ,
    XML10_ETAG_BEG                          ,
    XML10_ETAG_END                          ,
    XML10_ETag                              ,
    XML10_ETagBeg                           ,
    XML10_ETagEnd                           ,
    XML10_EdeclBeg                          ,
    XML10_EdeclEnd                          ,
    XML10_ElementDeclBeg                    ,
    XML10_ElementDeclEnd                    ,
    XML10_Empty                             ,
    XML10_EmptyElemTag                      ,
    XML10_EmptyElemTagBeg                   ,
    XML10_EmptyElemTagEnd                   ,
    XML10_EmptyElemTagInterior              ,
    XML10_EmptyElemTagInteriorAny           ,
    XML10_EncName                           ,
    XML10_Encoding                          ,
    XML10_EncodingDecl                      ,
    XML10_EncodingDeclMaybe                 ,
    XML10_EntityDecl                        ,
    XML10_EntityDef                         ,
    XML10_EntityRef                         ,
    XML10_EntityValue                       ,
    XML10_EnumeratedType                    ,
    XML10_Enumeration                       ,
    XML10_EnumerationInterior               ,
    XML10_EnumerationInteriorAny            ,
    XML10_Eq                                ,
    XML10_Equal                             ,
    XML10_ExternalID                        ,
    XML10_FIXED                             ,
    XML10_Fixed                             ,
    XML10_GEDecl                            ,
    XML10_IGNORE                            ,
    XML10_IGNORE_INTERIOR                   ,
    XML10_IMPLIED                           ,
    XML10_INCLUDE                           ,
    XML10_Ignore                            ,
    XML10_Implied                           ,
    XML10_Include                           ,
    XML10_LBRACKET                          ,
    XML10_LPAREN                            ,
    XML10_Lbracket                          ,
    XML10_Lparen                            ,
    XML10_Misc                              ,
    XML10_MiscAny                           ,
    XML10_Mixed                             ,
    XML10_MixedInterior                     ,
    XML10_MixedInteriorAny                  ,
    XML10_NAME                              ,
    XML10_NDATA                             ,
    XML10_NDataDecl                         ,
    XML10_NMTOKEN                           ,
    XML10_NO                                ,
    XML10_NOTATION                          ,
    XML10_NOTATION_BEG                      ,
    XML10_Name                              ,
    XML10_Names                             ,
    XML10_Ndata                             ,
    XML10_Nmtoken                           ,
    XML10_Nmtokens                          ,
    XML10_No                                ,
    XML10_Notation                          ,
    XML10_NotationBeg                       ,
    XML10_NotationDecl                      ,
    XML10_NotationEnd                       ,
    XML10_NotationType                      ,
    XML10_NotationTypeInterior              ,
    XML10_NotationTypeInteriorAny           ,
    XML10_PCDATA                            ,
    XML10_PEDecl                            ,
    XML10_PEDef                             ,
    XML10_PERCENT                           ,
    XML10_PEREFERENCE                       ,
    XML10_PEReference                       ,
    XML10_PI                                ,
    XML10_PIPE                              ,
    XML10_PITARGET                          ,
    XML10_PITarget                          ,
    XML10_PI_BEG                            ,
    XML10_PI_END                            ,
    XML10_PI_INTERIOR                       ,
    XML10_PLUS                              ,
    XML10_PUBIDLITERAL                      ,
    XML10_PUBLIC                            ,
    XML10_Pcdata                            ,
    XML10_Percent                           ,
    XML10_PiBeg                             ,
    XML10_PiEnd                             ,
    XML10_PiInterior                        ,
    XML10_Pipe                              ,
    XML10_Plus                              ,
    XML10_PubidLiteral                      ,
    XML10_Public                            ,
    XML10_PublicID                          ,
    XML10_QUESTION_MARK                     ,
    XML10_Quantifier                        ,
    XML10_QuantifierMaybe                   ,
    XML10_QuestionMark                      ,
    XML10_RBRACKET                          ,
    XML10_REQUIRED                          ,
    XML10_RPAREN                            ,
    XML10_RPARENSTAR                        ,
    XML10_Rbracket                          ,
    XML10_Reference                         ,
    XML10_Required                          ,
    XML10_Rparen                            ,
    XML10_RparenStar                        ,
    XML10_S                                 ,
    XML10_SDDecl                            ,
    XML10_SDDeclMaybe                       ,
    XML10_SECT_BEG                          ,
    XML10_SECT_END                          ,
    XML10_SMaybe                            ,
    XML10_SQUOTE                            ,
    XML10_STAG_END                          ,
    XML10_STANDALONE                        ,
    XML10_STAR                              ,
    XML10_STRINGTYPE                        ,
    XML10_STag                              ,
    XML10_STagBeg                           ,
    XML10_STagEnd                           ,
    XML10_STagInterior                      ,
    XML10_STagInteriorAny                   ,
    XML10_SYSTEM                            ,
    XML10_SYSTEMLITERAL                     ,
    XML10_SectBeg                           ,
    XML10_SectEnd                           ,
    XML10_SeqInterior                       ,
    XML10_SeqInteriorAny                    ,
    XML10_Squote                            ,
    XML10_Standalone                        ,
    XML10_Star                              ,
    XML10_StringType                        ,
    XML10_System                            ,
    XML10_SystemLiteral                     ,
    XML10_TOKIgnore                         ,
    XML10_TYPE_ENTITIES                     ,
    XML10_TYPE_ENTITY                       ,
    XML10_TYPE_ID                           ,
    XML10_TYPE_IDREF                        ,
    XML10_TYPE_IDREFS                       ,
    XML10_TYPE_NMTOKEN                      ,
    XML10_TYPE_NMTOKENS                     ,
    XML10_TextDecl                          ,
    XML10_TokenizedType                     ,
    XML10_TypeEntities                      ,
    XML10_TypeEntity                        ,
    XML10_TypeId                            ,
    XML10_TypeIdref                         ,
    XML10_TypeIdrefs                        ,
    XML10_TypeNmtoken                       ,
    XML10_TypeNmtokens                      ,
    XML10_VERSION                           ,
    XML10_VERSIONNUM                        ,
    XML10_Version                           ,
    XML10_VersionInfo                       ,
    XML10_VersionInfoMaybe                  ,
    XML10_VersionNum                        ,
    XML10_WhiteSpace                        ,
    XML10_X20                               ,
    XML10_XMLDecl                           ,
    XML10_XMLDeclMaybe                      ,
    XML10_XML_BEG                           ,
    XML10_XML_END                           ,
    XML10_XTAG_BEG                          ,
    XML10_XTAG_END                          ,
    XML10_XTagBeg                           ,
    XML10_XTagEnd                           ,
    XML10_XmlBeg                            ,
    XML10_XmlEnd                            ,
    XML10_YES                               ,
    XML10_Yes                               ,
    XML10___start_                          , /* [:start] (Internal G1 start symbol) */
    XML10_children                          ,
    XML10_choice                            ,
    XML10_conditionalSect                   ,
    XML10_content                           ,
    XML10_contentspec                       ,
    XML10_cp                                ,
    XML10_doctypedecl                       ,
    XML10_document                          ,
    XML10_element                           ,
    XML10_elementdecl                       ,
    XML10_extParsedEnt                      ,
    XML10_extSubset                         ,
    XML10_extSubsetDecl                     ,
    XML10_extSubsetDeclUnit                 ,
    XML10_extSubsetDeclUnitAny              ,
    XML10_ignoreSect                        ,
    XML10_ignoreSectContents                ,
    XML10_ignoreSectContentsAny             ,
    XML10_ignoreSectContentsInterior        ,
    XML10_ignoreSectContentsInteriorAny     ,
    XML10_includeSect                       ,
    XML10_intSubset                         ,
    XML10_intSubsetUnit                     ,
    XML10_intSubsetUnitAny                  ,
    XML10_markupdecl                        ,
    XML10_prolog                            ,
    XML10_seq                               ,
    XML10_x20                               ,
};
struct sXmlSymbolId aXml10SymbolId[] = {
   /*
    * Id, Enum                                    , Name                                    , Description
    */
    { -1, XML10_ANY                               , "ANY"                                   , "ANY" },
    { -1, XML10_ATTLIST_BEG                       , "ATTLIST_BEG"                           , "ATTLIST_BEG" },
    { -1, XML10_ATTVALUE                          , "ATTVALUE"                              , "ATTVALUE" },
    { -1, XML10_Any                               , "Any"                                   , "Any" },
    { -1, XML10_AttDef                            , "AttDef"                                , "AttDef" },
    { -1, XML10_AttDefAny                         , "AttDefAny"                             , "AttDefAny" },
    { -1, XML10_AttType                           , "AttType"                               , "AttType" },
    { -1, XML10_AttValue                          , "AttValue"                              , "AttValue" },
    { -1, XML10_AttlistBeg                        , "AttlistBeg"                            , "AttlistBeg" },
    { -1, XML10_AttlistDecl                       , "AttlistDecl"                           , "AttlistDecl" },
    { -1, XML10_AttlistEnd                        , "AttlistEnd"                            , "AttlistEnd" },
    { -1, XML10_Attribute                         , "Attribute"                             , "Attribute" },
    { -1, XML10_CDATA                             , "CDATA"                                 , "CDATA" },
    { -1, XML10_CDEND                             , "CDEND"                                 , "CDEND" },
    { -1, XML10_CDEnd                             , "CDEnd"                                 , "CDEnd" },
    { -1, XML10_CDSTART                           , "CDSTART"                               , "CDSTART" },
    { -1, XML10_CDSect                            , "CDSect"                                , "CDSect" },
    { -1, XML10_CDStart                           , "CDStart"                               , "CDStart" },
    { -1, XML10_CData                             , "CData"                                 , "CData" },
    { -1, XML10_CHAR                              , "CHAR"                                  , "CHAR" },
    { -1, XML10_CHARDATA                          , "CHARDATA"                              , "CHARDATA" },
    { -1, XML10_CHARREF                           , "CHARREF"                               , "CHARREF" },
    { -1, XML10_COMMA                             , "COMMA"                                 , "COMMA" },
    { -1, XML10_COMMENT                           , "COMMENT"                               , "COMMENT" },
    { -1, XML10_COMMENT_BEG                       , "COMMENT_BEG"                           , "COMMENT_BEG" },
    { -1, XML10_COMMENT_END                       , "COMMENT_END"                           , "COMMENT_END" },
    { -1, XML10_Char                              , "Char"                                  , "Char" },
    { -1, XML10_CharData                          , "CharData"                              , "CharData" },
    { -1, XML10_CharDataMaybe                     , "CharDataMaybe"                         , "CharDataMaybe" },
    { -1, XML10_CharRef                           , "CharRef"                               , "CharRef" },
    { -1, XML10_ChoiceInterior                    , "ChoiceInterior"                        , "ChoiceInterior" },
    { -1, XML10_ChoiceInteriorMany                , "ChoiceInteriorMany"                    , "ChoiceInteriorMany" },
    { -1, XML10_Comma                             , "Comma"                                 , "Comma" },
    { -1, XML10_Comment                           , "Comment"                               , "Comment" },
    { -1, XML10_CommentBeg                        , "CommentBeg"                            , "CommentBeg" },
    { -1, XML10_CommentEnd                        , "CommentEnd"                            , "CommentEnd" },
    { -1, XML10_CommentInterior                   , "CommentInterior"                       , "CommentInterior" },
    { -1, XML10_ContentInterior                   , "ContentInterior"                       , "ContentInterior" },
    { -1, XML10_ContentInteriorAny                , "ContentInteriorAny"                    , "ContentInteriorAny" },
    { -1, XML10_DOCTYPE_BEG                       , "DOCTYPE_BEG"                           , "DOCTYPE_BEG" },
    { -1, XML10_DQUOTE                            , "DQUOTE"                                , "DQUOTE" },
    { -1, XML10_DeclSep                           , "DeclSep"                               , "DeclSep" },
    { -1, XML10_DefaultDecl                       , "DefaultDecl"                           , "DefaultDecl" },
    { -1, XML10_DoctypeBeg                        , "DoctypeBeg"                            , "DoctypeBeg" },
    { -1, XML10_DoctypeEnd                        , "DoctypeEnd"                            , "DoctypeEnd" },
    { -1, XML10_Dquote                            , "Dquote"                                , "Dquote" },
    { -1, XML10_EDECL_BEG                         , "EDECL_BEG"                             , "EDECL_BEG" },
    { -1, XML10_ELEMENTDECL_BEG                   , "ELEMENTDECL_BEG"                       , "ELEMENTDECL_BEG" },
    { -1, XML10_EMPTY                             , "EMPTY"                                 , "EMPTY" },
    { -1, XML10_EMPTYELEMTAG_END                  , "EMPTYELEMTAG_END"                      , "EMPTYELEMTAG_END" },
    { -1, XML10_ENCNAME                           , "ENCNAME"                               , "ENCNAME" },
    { -1, XML10_ENCODING                          , "ENCODING"                              , "ENCODING" },
    { -1, XML10_ENTITYREF                         , "ENTITYREF"                             , "ENTITYREF" },
    { -1, XML10_ENTITYVALUE                       , "ENTITYVALUE"                           , "ENTITYVALUE" },
    { -1, XML10_EQUAL                             , "EQUAL"                                 , "EQUAL" },
    { -1, XML10_ETAG_BEG                          , "ETAG_BEG"                              , "ETAG_BEG" },
    { -1, XML10_ETAG_END                          , "ETAG_END"                              , "ETAG_END" },
    { -1, XML10_ETag                              , "ETag"                                  , "ETag" },
    { -1, XML10_ETagBeg                           , "ETagBeg"                               , "ETagBeg" },
    { -1, XML10_ETagEnd                           , "ETagEnd"                               , "ETagEnd" },
    { -1, XML10_EdeclBeg                          , "EdeclBeg"                              , "EdeclBeg" },
    { -1, XML10_EdeclEnd                          , "EdeclEnd"                              , "EdeclEnd" },
    { -1, XML10_ElementDeclBeg                    , "ElementDeclBeg"                        , "ElementDeclBeg" },
    { -1, XML10_ElementDeclEnd                    , "ElementDeclEnd"                        , "ElementDeclEnd" },
    { -1, XML10_Empty                             , "Empty"                                 , "Empty" },
    { -1, XML10_EmptyElemTag                      , "EmptyElemTag"                          , "EmptyElemTag" },
    { -1, XML10_EmptyElemTagBeg                   , "EmptyElemTagBeg"                       , "EmptyElemTagBeg" },
    { -1, XML10_EmptyElemTagEnd                   , "EmptyElemTagEnd"                       , "EmptyElemTagEnd" },
    { -1, XML10_EmptyElemTagInterior              , "EmptyElemTagInterior"                  , "EmptyElemTagInterior" },
    { -1, XML10_EmptyElemTagInteriorAny           , "EmptyElemTagInteriorAny"               , "EmptyElemTagInteriorAny" },
    { -1, XML10_EncName                           , "EncName"                               , "EncName" },
    { -1, XML10_Encoding                          , "Encoding"                              , "Encoding" },
    { -1, XML10_EncodingDecl                      , "EncodingDecl"                          , "EncodingDecl" },
    { -1, XML10_EncodingDeclMaybe                 , "EncodingDeclMaybe"                     , "EncodingDeclMaybe" },
    { -1, XML10_EntityDecl                        , "EntityDecl"                            , "EntityDecl" },
    { -1, XML10_EntityDef                         , "EntityDef"                             , "EntityDef" },
    { -1, XML10_EntityRef                         , "EntityRef"                             , "EntityRef" },
    { -1, XML10_EntityValue                       , "EntityValue"                           , "EntityValue" },
    { -1, XML10_EnumeratedType                    , "EnumeratedType"                        , "EnumeratedType" },
    { -1, XML10_Enumeration                       , "Enumeration"                           , "Enumeration" },
    { -1, XML10_EnumerationInterior               , "EnumerationInterior"                   , "EnumerationInterior" },
    { -1, XML10_EnumerationInteriorAny            , "EnumerationInteriorAny"                , "EnumerationInteriorAny" },
    { -1, XML10_Eq                                , "Eq"                                    , "Eq" },
    { -1, XML10_Equal                             , "Equal"                                 , "Equal" },
    { -1, XML10_ExternalID                        , "ExternalID"                            , "ExternalID" },
    { -1, XML10_FIXED                             , "FIXED"                                 , "FIXED" },
    { -1, XML10_Fixed                             , "Fixed"                                 , "Fixed" },
    { -1, XML10_GEDecl                            , "GEDecl"                                , "GEDecl" },
    { -1, XML10_IGNORE                            , "IGNORE"                                , "IGNORE" },
    { -1, XML10_IGNORE_INTERIOR                   , "IGNORE_INTERIOR"                       , "IGNORE_INTERIOR" },
    { -1, XML10_IMPLIED                           , "IMPLIED"                               , "IMPLIED" },
    { -1, XML10_INCLUDE                           , "INCLUDE"                               , "INCLUDE" },
    { -1, XML10_Ignore                            , "Ignore"                                , "Ignore" },
    { -1, XML10_Implied                           , "Implied"                               , "Implied" },
    { -1, XML10_Include                           , "Include"                               , "Include" },
    { -1, XML10_LBRACKET                          , "LBRACKET"                              , "LBRACKET" },
    { -1, XML10_LPAREN                            , "LPAREN"                                , "LPAREN" },
    { -1, XML10_Lbracket                          , "Lbracket"                              , "Lbracket" },
    { -1, XML10_Lparen                            , "Lparen"                                , "Lparen" },
    { -1, XML10_Misc                              , "Misc"                                  , "Misc" },
    { -1, XML10_MiscAny                           , "MiscAny"                               , "MiscAny" },
    { -1, XML10_Mixed                             , "Mixed"                                 , "Mixed" },
    { -1, XML10_MixedInterior                     , "MixedInterior"                         , "MixedInterior" },
    { -1, XML10_MixedInteriorAny                  , "MixedInteriorAny"                      , "MixedInteriorAny" },
    { -1, XML10_NAME                              , "NAME"                                  , "NAME" },
    { -1, XML10_NDATA                             , "NDATA"                                 , "NDATA" },
    { -1, XML10_NDataDecl                         , "NDataDecl"                             , "NDataDecl" },
    { -1, XML10_NMTOKEN                           , "NMTOKEN"                               , "NMTOKEN" },
    { -1, XML10_NO                                , "NO"                                    , "NO" },
    { -1, XML10_NOTATION                          , "NOTATION"                              , "NOTATION" },
    { -1, XML10_NOTATION_BEG                      , "NOTATION_BEG"                          , "NOTATION_BEG" },
    { -1, XML10_Name                              , "Name"                                  , "Name" },
    { -1, XML10_Names                             , "Names"                                 , "Names" },
    { -1, XML10_Ndata                             , "Ndata"                                 , "Ndata" },
    { -1, XML10_Nmtoken                           , "Nmtoken"                               , "Nmtoken" },
    { -1, XML10_Nmtokens                          , "Nmtokens"                              , "Nmtokens" },
    { -1, XML10_No                                , "No"                                    , "No" },
    { -1, XML10_Notation                          , "Notation"                              , "Notation" },
    { -1, XML10_NotationBeg                       , "NotationBeg"                           , "NotationBeg" },
    { -1, XML10_NotationDecl                      , "NotationDecl"                          , "NotationDecl" },
    { -1, XML10_NotationEnd                       , "NotationEnd"                           , "NotationEnd" },
    { -1, XML10_NotationType                      , "NotationType"                          , "NotationType" },
    { -1, XML10_NotationTypeInterior              , "NotationTypeInterior"                  , "NotationTypeInterior" },
    { -1, XML10_NotationTypeInteriorAny           , "NotationTypeInteriorAny"               , "NotationTypeInteriorAny" },
    { -1, XML10_PCDATA                            , "PCDATA"                                , "PCDATA" },
    { -1, XML10_PEDecl                            , "PEDecl"                                , "PEDecl" },
    { -1, XML10_PEDef                             , "PEDef"                                 , "PEDef" },
    { -1, XML10_PERCENT                           , "PERCENT"                               , "PERCENT" },
    { -1, XML10_PEREFERENCE                       , "PEREFERENCE"                           , "PEREFERENCE" },
    { -1, XML10_PEReference                       , "PEReference"                           , "PEReference" },
    { -1, XML10_PI                                , "PI"                                    , "PI" },
    { -1, XML10_PIPE                              , "PIPE"                                  , "PIPE" },
    { -1, XML10_PITARGET                          , "PITARGET"                              , "PITARGET" },
    { -1, XML10_PITarget                          , "PITarget"                              , "PITarget" },
    { -1, XML10_PI_BEG                            , "PI_BEG"                                , "PI_BEG" },
    { -1, XML10_PI_END                            , "PI_END"                                , "PI_END" },
    { -1, XML10_PI_INTERIOR                       , "PI_INTERIOR"                           , "PI_INTERIOR" },
    { -1, XML10_PLUS                              , "PLUS"                                  , "PLUS" },
    { -1, XML10_PUBIDLITERAL                      , "PUBIDLITERAL"                          , "PUBIDLITERAL" },
    { -1, XML10_PUBLIC                            , "PUBLIC"                                , "PUBLIC" },
    { -1, XML10_Pcdata                            , "Pcdata"                                , "Pcdata" },
    { -1, XML10_Percent                           , "Percent"                               , "Percent" },
    { -1, XML10_PiBeg                             , "PiBeg"                                 , "PiBeg" },
    { -1, XML10_PiEnd                             , "PiEnd"                                 , "PiEnd" },
    { -1, XML10_PiInterior                        , "PiInterior"                            , "PiInterior" },
    { -1, XML10_Pipe                              , "Pipe"                                  , "Pipe" },
    { -1, XML10_Plus                              , "Plus"                                  , "Plus" },
    { -1, XML10_PubidLiteral                      , "PubidLiteral"                          , "PubidLiteral" },
    { -1, XML10_Public                            , "Public"                                , "Public" },
    { -1, XML10_PublicID                          , "PublicID"                              , "PublicID" },
    { -1, XML10_QUESTION_MARK                     , "QUESTION_MARK"                         , "QUESTION_MARK" },
    { -1, XML10_Quantifier                        , "Quantifier"                            , "Quantifier" },
    { -1, XML10_QuantifierMaybe                   , "QuantifierMaybe"                       , "QuantifierMaybe" },
    { -1, XML10_QuestionMark                      , "QuestionMark"                          , "QuestionMark" },
    { -1, XML10_RBRACKET                          , "RBRACKET"                              , "RBRACKET" },
    { -1, XML10_REQUIRED                          , "REQUIRED"                              , "REQUIRED" },
    { -1, XML10_RPAREN                            , "RPAREN"                                , "RPAREN" },
    { -1, XML10_RPARENSTAR                        , "RPARENSTAR"                            , "RPARENSTAR" },
    { -1, XML10_Rbracket                          , "Rbracket"                              , "Rbracket" },
    { -1, XML10_Reference                         , "Reference"                             , "Reference" },
    { -1, XML10_Required                          , "Required"                              , "Required" },
    { -1, XML10_Rparen                            , "Rparen"                                , "Rparen" },
    { -1, XML10_RparenStar                        , "RparenStar"                            , "RparenStar" },
    { -1, XML10_S                                 , "S"                                     , "S" },
    { -1, XML10_SDDecl                            , "SDDecl"                                , "SDDecl" },
    { -1, XML10_SDDeclMaybe                       , "SDDeclMaybe"                           , "SDDeclMaybe" },
    { -1, XML10_SECT_BEG                          , "SECT_BEG"                              , "SECT_BEG" },
    { -1, XML10_SECT_END                          , "SECT_END"                              , "SECT_END" },
    { -1, XML10_SMaybe                            , "SMaybe"                                , "SMaybe" },
    { -1, XML10_SQUOTE                            , "SQUOTE"                                , "SQUOTE" },
    { -1, XML10_STAG_END                          , "STAG_END"                              , "STAG_END" },
    { -1, XML10_STANDALONE                        , "STANDALONE"                            , "STANDALONE" },
    { -1, XML10_STAR                              , "STAR"                                  , "STAR" },
    { -1, XML10_STRINGTYPE                        , "STRINGTYPE"                            , "STRINGTYPE" },
    { -1, XML10_STag                              , "STag"                                  , "STag" },
    { -1, XML10_STagBeg                           , "STagBeg"                               , "STagBeg" },
    { -1, XML10_STagEnd                           , "STagEnd"                               , "STagEnd" },
    { -1, XML10_STagInterior                      , "STagInterior"                          , "STagInterior" },
    { -1, XML10_STagInteriorAny                   , "STagInteriorAny"                       , "STagInteriorAny" },
    { -1, XML10_SYSTEM                            , "SYSTEM"                                , "SYSTEM" },
    { -1, XML10_SYSTEMLITERAL                     , "SYSTEMLITERAL"                         , "SYSTEMLITERAL" },
    { -1, XML10_SectBeg                           , "SectBeg"                               , "SectBeg" },
    { -1, XML10_SectEnd                           , "SectEnd"                               , "SectEnd" },
    { -1, XML10_SeqInterior                       , "SeqInterior"                           , "SeqInterior" },
    { -1, XML10_SeqInteriorAny                    , "SeqInteriorAny"                        , "SeqInteriorAny" },
    { -1, XML10_Squote                            , "Squote"                                , "Squote" },
    { -1, XML10_Standalone                        , "Standalone"                            , "Standalone" },
    { -1, XML10_Star                              , "Star"                                  , "Star" },
    { -1, XML10_StringType                        , "StringType"                            , "StringType" },
    { -1, XML10_System                            , "System"                                , "System" },
    { -1, XML10_SystemLiteral                     , "SystemLiteral"                         , "SystemLiteral" },
    { -1, XML10_TOKIgnore                         , "TOKIgnore"                             , "TOKIgnore" },
    { -1, XML10_TYPE_ENTITIES                     , "TYPE_ENTITIES"                         , "TYPE_ENTITIES" },
    { -1, XML10_TYPE_ENTITY                       , "TYPE_ENTITY"                           , "TYPE_ENTITY" },
    { -1, XML10_TYPE_ID                           , "TYPE_ID"                               , "TYPE_ID" },
    { -1, XML10_TYPE_IDREF                        , "TYPE_IDREF"                            , "TYPE_IDREF" },
    { -1, XML10_TYPE_IDREFS                       , "TYPE_IDREFS"                           , "TYPE_IDREFS" },
    { -1, XML10_TYPE_NMTOKEN                      , "TYPE_NMTOKEN"                          , "TYPE_NMTOKEN" },
    { -1, XML10_TYPE_NMTOKENS                     , "TYPE_NMTOKENS"                         , "TYPE_NMTOKENS" },
    { -1, XML10_TextDecl                          , "TextDecl"                              , "TextDecl" },
    { -1, XML10_TokenizedType                     , "TokenizedType"                         , "TokenizedType" },
    { -1, XML10_TypeEntities                      , "TypeEntities"                          , "TypeEntities" },
    { -1, XML10_TypeEntity                        , "TypeEntity"                            , "TypeEntity" },
    { -1, XML10_TypeId                            , "TypeId"                                , "TypeId" },
    { -1, XML10_TypeIdref                         , "TypeIdref"                             , "TypeIdref" },
    { -1, XML10_TypeIdrefs                        , "TypeIdrefs"                            , "TypeIdrefs" },
    { -1, XML10_TypeNmtoken                       , "TypeNmtoken"                           , "TypeNmtoken" },
    { -1, XML10_TypeNmtokens                      , "TypeNmtokens"                          , "TypeNmtokens" },
    { -1, XML10_VERSION                           , "VERSION"                               , "VERSION" },
    { -1, XML10_VERSIONNUM                        , "VERSIONNUM"                            , "VERSIONNUM" },
    { -1, XML10_Version                           , "Version"                               , "Version" },
    { -1, XML10_VersionInfo                       , "VersionInfo"                           , "VersionInfo" },
    { -1, XML10_VersionInfoMaybe                  , "VersionInfoMaybe"                      , "VersionInfoMaybe" },
    { -1, XML10_VersionNum                        , "VersionNum"                            , "VersionNum" },
    { -1, XML10_WhiteSpace                        , "WhiteSpace"                            , "WhiteSpace" },
    { -1, XML10_X20                               , "X20"                                   , "X20" },
    { -1, XML10_XMLDecl                           , "XMLDecl"                               , "XMLDecl" },
    { -1, XML10_XMLDeclMaybe                      , "XMLDeclMaybe"                          , "XMLDeclMaybe" },
    { -1, XML10_XML_BEG                           , "XML_BEG"                               , "XML_BEG" },
    { -1, XML10_XML_END                           , "XML_END"                               , "XML_END" },
    { -1, XML10_XTAG_BEG                          , "XTAG_BEG"                              , "XTAG_BEG" },
    { -1, XML10_XTAG_END                          , "XTAG_END"                              , "XTAG_END" },
    { -1, XML10_XTagBeg                           , "XTagBeg"                               , "XTagBeg" },
    { -1, XML10_XTagEnd                           , "XTagEnd"                               , "XTagEnd" },
    { -1, XML10_XmlBeg                            , "XmlBeg"                                , "XmlBeg" },
    { -1, XML10_XmlEnd                            , "XmlEnd"                                , "XmlEnd" },
    { -1, XML10_YES                               , "YES"                                   , "YES" },
    { -1, XML10_Yes                               , "Yes"                                   , "Yes" },
    { -1, XML10___start_                          , "[:start]"                              , "Internal G1 start symbol" },
    { -1, XML10_children                          , "children"                              , "children" },
    { -1, XML10_choice                            , "choice"                                , "choice" },
    { -1, XML10_conditionalSect                   , "conditionalSect"                       , "conditionalSect" },
    { -1, XML10_content                           , "content"                               , "content" },
    { -1, XML10_contentspec                       , "contentspec"                           , "contentspec" },
    { -1, XML10_cp                                , "cp"                                    , "cp" },
    { -1, XML10_doctypedecl                       , "doctypedecl"                           , "doctypedecl" },
    { -1, XML10_document                          , "document"                              , "document" },
    { -1, XML10_element                           , "element"                               , "element" },
    { -1, XML10_elementdecl                       , "elementdecl"                           , "elementdecl" },
    { -1, XML10_extParsedEnt                      , "extParsedEnt"                          , "extParsedEnt" },
    { -1, XML10_extSubset                         , "extSubset"                             , "extSubset" },
    { -1, XML10_extSubsetDecl                     , "extSubsetDecl"                         , "extSubsetDecl" },
    { -1, XML10_extSubsetDeclUnit                 , "extSubsetDeclUnit"                     , "extSubsetDeclUnit" },
    { -1, XML10_extSubsetDeclUnitAny              , "extSubsetDeclUnitAny"                  , "extSubsetDeclUnitAny" },
    { -1, XML10_ignoreSect                        , "ignoreSect"                            , "ignoreSect" },
    { -1, XML10_ignoreSectContents                , "ignoreSectContents"                    , "ignoreSectContents" },
    { -1, XML10_ignoreSectContentsAny             , "ignoreSectContentsAny"                 , "ignoreSectContentsAny" },
    { -1, XML10_ignoreSectContentsInterior        , "ignoreSectContentsInterior"            , "ignoreSectContentsInterior" },
    { -1, XML10_ignoreSectContentsInteriorAny     , "ignoreSectContentsInteriorAny"         , "ignoreSectContentsInteriorAny" },
    { -1, XML10_includeSect                       , "includeSect"                           , "includeSect" },
    { -1, XML10_intSubset                         , "intSubset"                             , "intSubset" },
    { -1, XML10_intSubsetUnit                     , "intSubsetUnit"                         , "intSubsetUnit" },
    { -1, XML10_intSubsetUnitAny                  , "intSubsetUnitAny"                      , "intSubsetUnitAny" },
    { -1, XML10_markupdecl                        , "markupdecl"                            , "markupdecl" },
    { -1, XML10_prolog                            , "prolog"                                , "prolog" },
    { -1, XML10_seq                               , "seq"                                   , "seq" },
    { -1, XML10_x20                               , "x20"                                   , "x20" },
};

#define XML10_NUMBER_OF_SYMBOLS 257

#endif /* XML10_H */
